### PR TITLE
WIP V2

### PR DESCRIPTION
**Pull request by kristianmandrup**
Updating router to v2 API

http://router.vuejs.org/en/essentials/getting-started.html

WIP. Needs testing

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thanks for making this PR. I am going to ask you to wait a little. I will make separate repos for each starter kit from now on. Will then update CLI to work with separate repos. "rstoenescu/quasar-kit-default" will be used for Vue 2, so any work should go in there.

**Comment by rstoenescu** [comment]
Repo ready: rstoenescu/quasar-kit-default
Vue 2 work for the template should be done there. Thanks a lot for your help!

**Comment by kristianmandrup** [comment]
Sure. I was just playing trying to get an overview of your repos and architecture. You are welcome to take bits and pieces from my PRs as you like.
Cheers!

**Comment by rstoenescu** [comment]
Thanks!

**Pull request closed without merging**
